apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nuxt-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nuxt-sample
    app.kubernetes.io/part-of: nuxt-sample
  name: nuxt-sample
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nuxt-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nuxt-sample
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/johnmcollier-tenant/nuxt-sample/nuxt-sample@sha256:53e80ef621ae0d4fde562a8ab37692a8a991491bca07f12dd95cf7e38a807790
        name: my-nodejs
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
