apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nuxt-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nuxt-sample
    app.kubernetes.io/part-of: nuxt-sample
  name: nuxt-samplem7ll
spec:
  path: /
  port:
    targetPort: 3000
  to:
    kind: Service
    name: nuxt-sample
    weight: null
status: {}
